export default [
    {
        city: "NT",
        state: "TW",
        district: "TSW",
        name: "Tsuen Wan",
    },
    {
        city: "NT",
        state: "TW",
        district: "SHTS",
        name: "Sham Tseng",
    },
    {
        city: "NT",
        state: "KWTS",
        district: "TSY",
        name: "Tsing Yi",
    },
    {
        city: "NT",
        state: "KWTS",
        district: "KWC",
        name: "Kwai Chung",
    },
    {
        city: "NT",
        state: "KWTS",
        district: "TWH",
        name: "Tai Wo Hau",
    },
    {
        city: "NT",
        state: "KWTS",
        district: "KWH",
        name: "Kwai Hing",
    },
    {
        city: "NT",
        state: "KWTS",
        district: "KWF",
        name: "Kwai Fong",
    },
    {
        city: "NT",
        state: "KWTS",
        district: "LAK",
        name: "Lai King",
    },
    {
        city: "NT",
        state: "ST",
        district: "SHT",
        name: "Sha Tin",
    },
    {
        city: "NT",
        state: "ST",
        district: "TAW",
        name: "Tai Wai",
    },
    {
        city: "NT",
        state: "ST",
        district: "FOT",
        name: "Fo Tan",
    },
    {
        city: "NT",
        state: "ST",
        district: "SHM",
        name: "Shek Mun",
    },
    {
        city: "NT",
        state: "ST",
        district: "SLY",
        name: "Siu Lek Yuen",
    },
    {
        city: "NT",
        state: "ST",
        district: "MLS",
        name: "Ma Liu Shui",
    },
    {
        city: "NT",
        state: "ST",
        district: "MOS",
        name: "Ma On Shan",
    },
    {
        city: "NT",
        state: "TM",
        district: "TUM",
        name: "Tuen Mun",
    },
    {
        city: "NT",
        state: "YL",
        district: "YUL",
        name: "Yuen Long",
    },
    {
        city: "NT",
        state: "YL",
        district: "TIS",
        name: "Tin Shui Wai",
    },
    {
        city: "NT",
        state: "YL",
        district: "HSK",
        name: "Hung Shui Kiu",
    },
    {
        city: "NT",
        state: "N",
        district: "SHS",
        name: "Sheung Shui",
    },
    {
        city: "NT",
        state: "N",
        district: "FAN",
        name: "Fanling",
    },
    {
        city: "NT",
        state: "TP",
        district: "TAP",
        name: "Tai Po",
    },
    {
        city: "NT",
        state: "SKS",
        district: "TKO",
        name: "Tseung Kwan O",
    },
    {
        city: "NT",
        state: "SKS",
        district: "HAH",
        name: "Hang Hau",
    },
    {
        city: "NT",
        state: "SKS",
        district: "TIK",
        name: "Tiu Keng Leng",
    },
    {
        city: "NT",
        state: "SKS",
        district: "LHP",
        name: "LOHAS Park",
    },
    {
        city: "NT",
        state: "SKS",
        district: "SAK",
        name: "Tiu Keng Leng",
    },
    {
        city: "NT",
        state: "SKS",
        district: "CWB",
        name: "Clear Water Bay",
    },
    {
        city: "KLN",
        state: "SSPS",
        district: "MEF",
        name: "Mei Foo",
    },
    {
        city: "KLN",
        state: "SSPS",
        district: "LCK",
        name: "Lai Chi Kok",
    },
    {
        city: "KLN",
        state: "SSPS",
        district: "CSW",
        name: "Cheung Sha Wan",
    },
    {
        city: "KLN",
        state: "SSPS",
        district: "SSP",
        name: "Sham Shui Po",
    },
    {
        city: "KLN",
        state: "SSPS",
        district: "SKM",
        name: "Shek Kip Mei",
    },
    {
        city: "KLN",
        state: "SSPS",
        district: "NAC",
        name: "Nam Cheong",
    },
    {
        city: "KLN",
        state: "YTM",
        district: "PRE",
        name: "Prince Edward",
    },
    {
        city: "KLN",
        state: "YTM",
        district: "MOK",
        name: "Mong Kok",
    },
    {
        city: "KLN",
        state: "YTM",
        district: "YMT",
        name: "Yau Ma Tei",
    },
    {
        city: "KLN",
        state: "YTM",
        district: "JOR",
        name: "Jordan",
    },
    {
        city: "KLN",
        state: "YTM",
        district: "TKT",
        name: "Tai Kok Tsui",
    },
    {
        city: "KLN",
        state: "YTM",
        district: "TST",
        name: "Tsim Sha Tsui",
    },
    {
        city: "KLN",
        state: "YTM",
        district: "AUS",
        name: "Austin",
    },
    {
        city: "KLN",
        state: "KC",
        district: "KOT",
        name: "Kowloon Tong",
    },
    {
        city: "KLN",
        state: "KC",
        district: "HUH",
        name: "Hung Hom",
    },
    {
        city: "KLN",
        state: "KC",
        district: "HOM",
        name: "Ho Man Tin",
    },
    {
        city: "KLN",
        state: "KC",
        district: "To Kwa Wan",
    },
    {
        city: "KLN",
        state: "KC",
        district: "KLNC",
        name: "Kowloon City",
    },
    {
        city: "KLN",
        state: "KC",
        district: "KAT",
        name: "Kai Tak",
    },
    {
        city: "KLN",
        state: "KC",
        district: "WHA",
        name: "Whampoa",
    },
    {
        city: "KLN",
        state: "WTS",
        district: "LOF",
        name: "Lok Fu",
    },
    {
        city: "KLN",
        state: "WTS",
        district: "WTS",
        name: "Wong Tai Sin",
    },
    {
        city: "KLN",
        state: "WTS",
        district: "CHH",
        name: "Choi Hung",
    },
    {
        city: "KLN",
        state: "WTS",
        district: "NCW",
        name: "Ngau Chi Wan",
    },
    {
        city: "KLN",
        state: "WTS",
        district: "TWS",
        name: "Tsz Wan Shan",
    },
    {
        city: "KLN",
        state: "WTS",
        district: "DIH",
        name: "Diamond Hill",
    },
    {
        city: "KLN",
        state: "WTS",
        district: "SPK",
        name: "San Po Kong",
    },
    {
        city: "KLN",
        state: "KTS",
        district: "KOB",
        name: "Kowloon Bay",
    },
    {
        city: "KLN",
        state: "KTS",
        district: "NTK",
        name: "Ngau Tau Kok",
    },
    {
        city: "KLN",
        state: "KTS",
        district: "KWT",
        name: "Kwun Tong",
    },
    {
        city: "KLN",
        state: "KTS",
        district: "SMP",
        name: "Sau Mau Ping",
    },
    {
        city: "KLN",
        state: "KTS",
        district: "LAT",
        name: "Lam Tin",
    },
    {
        city: "KLN",
        state: "KTS",
        district: "YAT",
        name: "Yau Tong",
    },
    {
        city: "KLN",
        state: "KTS",
        district: "SHL",
        name: "Shun Lee",
    },
    {
        city: "HKI",
        state: "CW",
        district: "CEN",
        name: "Central",
    },
    {
        city: "HKI",
        state: "CW",
        district: "SHW",
        name: "Sheung Wan",
    },
    {
        city: "HKI",
        state: "CW",
        district: "SAW",
        name: "Sai Wan",
    },
    {
        city: "HKI",
        state: "CW",
        district: "SYP",
        name: "Sai Ying Pun",
    },
    {
        city: "HKI",
        state: "CW",
        district: "KET",
        name: "Kennedy Town",
    },
    {
        city: "HKI",
        state: "CW",
        district: "MID",
        name: "Mid-levels",
    },
    {
        city: "HKI",
        state: "WCS",
        district: "WC",
        name: "Wan Chai",
    },
    {
        city: "HKI",
        state: "WCS",
        district: "CAB",
        name: "Causeway Bay",
    },
    {
        city: "HKI",
        state: "WCS",
        district: "TIH",
        name: "Tin Hau",
    },
    {
        city: "HKI",
        state: "WCS",
        district: "TH",
        name: "Tai Hang",
    },
    {
        city: "HKI",
        state: "WCS",
        district: "HVA",
        name: "Happy Valley",
    },
    {
        city: "HKI",
        state: "E",
        district: "FOH",
        name: "Fortress Hill",
    },
    {
        city: "HKI",
        state: "E",
        district: "NOP",
        name: "North Point",
    },
    {
        city: "HKI",
        state: "E",
        district: "QUB",
        name: "Quarry Bay",
    },
    {
        city: "HKI",
        state: "E",
        district: "TK",
        name: "Tai Koo",
    },
    {
        city: "HKI",
        state: "E",
        district: "SWH",
        name: "Sai Wan Ho",
    },
    {
        city: "HKI",
        state: "E",
        district: "SKW",
        name: "Shau Kei Wan",
    },
    {
        city: "HKI",
        state: "E",
        district: "HFC",
        name: "Heng Fa Chuen",
    },
    {
        city: "HKI",
        state: "E",
        district: "CHW",
        name: "Chai Wan",
    },
    {
        city: "HKI",
        state: "E",
        district: "SSW",
        name: "Siu Sai Wan",
    },
    {
        city: "HKI",
        state: "S",
        district: "PFL",
        name: "Pok Fu Lam",
    },
    {
        city: "HKI",
        state: "S",
        district: "WCH",
        name: "Wong Chuk Hang",
    },
    {
        city: "HKI",
        state: "S",
        district: "ALC",
        name: "Ap Lei Chau",
    },
    {
        city: "HKI",
        state: "S",
        district: "ABE",
        name: "Aberdeen",
    },
    {
        city: "HKI",
        state: "S",
        district: "SO",
        name: "Shek O",
    },
    {
        city: "HKI",
        state: "S",
        district: "TT",
        name: "Tai Tam",
    },
    {
        city: "HKI",
        state: "S",
        district: "SL",
        name: "Stanley",
    },
    {
        city: "ISL",
        district: "MW",
        name: "Ma Wan",
    },
    {
        city: "ISL",
        district: "CC",
        name: "Cheung Chau",
    },
    {
        city: "ISL",
        district: "TC",
        name: "Tung Chung",
    },
    {
        city: "ISL",
        district: "CLK",
        name: "Chek Lap Kok",
    },
    {
        city: "ISL",
        district: "MWO",
        name: "Mui Wo",
    },
    {
        city: "ISL",
        district: "PO",
        name: "Pui O",
    },
    {
        city: "ISL",
        district: "DISB",
        name: "Discovery Bay",
    },
    {
        city: "ISL",
        district: "LI",
        name: "Lamma Island",
    },
    {
        city: "ISL",
        district: "PC",
        name: "Peng Chau",
    },
];
